
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "lazy_core"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
bytes = "1.10.1"
fast_image_resize = "5.2.0"
futures = "0.3.31"
image = { version = "0.25.6", default-features = true, features = ["avif-native"]}
napi = "3.0.0"
napi-derive = "3.0.0"
once_cell = "1.21.3"
oxc = { version = "0.74.0", features = ["full"] }
reqwest = { version = "0.12.22", features = ["blocking", "rustls-tls"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread", "tokio-macros"] }
url = "2.5.4"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
