/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function plus100(input: number): number

export declare function transform(code: string, filePath: string): TransformOutput | null

export interface TransformOptions {
  code: string
  filePath: string
}

export interface TransformOutput {
  code: string
  sourcemap?: string
}
