/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Log {
  message: string
  level: LogLevel
}

export declare const enum LogLevel {
  None = 0,
  Error = 1,
  Info = 2,
  Verbose = 3
}

export declare const enum PlaceholderImageOutputKind {
  Normal = 0,
  Blurred = 1,
  Grayscale = 2,
  DominantColor = 3,
  AverageColor = 4,
  Transparent = 5
}

export interface PreviewOptions {
  width?: number
  height?: number
  outputKind: PlaceholderImageOutputKind
  replaceFunctionCall: boolean
  cache: boolean
  wrapWithSvg: boolean
}

export declare function transform(code: string, filePath: string, options: TransformOptions): TransformOutput | null

export interface TransformOptions {
  placeholderType?: PlaceholderImageOutputKind
  replaceFunctionCall?: boolean
  cache?: boolean
  publicDir?: string
  cacheFileDir?: string
  logLevel?: LogLevel
  width?: number
  height?: number
  sourcemapFilePath?: string
  wrapWithSvg?: boolean
}

export interface TransformOutput {
  code: string
  sourcemap?: string
  logs?: Array<Log>
}
