name: PR CI

on:
  pull_request:
    branches: [master]

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test core package
        working-directory: ./packages/core
        run: |
          yarn
          yarn build
          yarn test