name: PR CI

on:
  pull_request:
    branches: [master]

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install
      - name: Biome check
        run: pnpm biome:check
      - name: Build core package
        run: pnpm --filter @nocojs/core build
      - name: Test core package
        run: pnpm --filter @nocojs/core test